In [1]:
import numpy as np 
import pandas as pd

In [2]:
train = pd.read_csv('stock_train.csv')
test = pd.read_csv('stock_test.csv')

In [3]:
train

           Date     Close
0    2024-01-02  10000.00
1    2024-01-03  10024.38
2    2024-01-04   9940.98
3    2024-01-05  10014.32
4    2024-01-06   9883.17
..          ...       ...
298  2024-10-26  20598.10
299  2024-10-27  20424.36
300  2024-10-28  20786.96
301  2024-10-29  20753.59
302  2024-10-30  20991.90

[303 rows x 2 columns]

In [4]:
train['r'] = train['Close'].diff(1)/train['Close'].shift(1)

In [5]:
train

           Date     Close         r
0    2024-01-02  10000.00       NaN
1    2024-01-03  10024.38  0.002438
2    2024-01-04   9940.98 -0.008320
3    2024-01-05  10014.32  0.007378
4    2024-01-06   9883.17 -0.013096
..          ...       ...       ...
298  2024-10-26  20598.10 -0.004882
299  2024-10-27  20424.36 -0.008435
300  2024-10-28  20786.96  0.017753
301  2024-10-29  20753.59 -0.001605
302  2024-10-30  20991.90  0.011483

[303 rows x 3 columns]

In [6]:
A = np.zeros((train.shape[0] - 3, 6))

In [7]:
r = train["Close"].pct_change().to_numpy()

In [8]:
b = train['r'].to_numpy()[3:]

In [9]:
for i, t in enumerate(range(3, len(r))):
      lag1, lag2 = r[t - 1], r[t - 2]
      if lag1 >= 0:
          A[i, :3] = [1, lag1, lag2]
      else:
          A[i, 3:] = [1, lag1, lag2]

In [10]:
A

array([[ 0.        ,  0.        ,  0.        ,  1.        , -0.00831972,
         0.002438  ],
       [ 1.        ,  0.00737754, -0.00831972,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        , -0.01309625,
         0.00737754],
       ...,
       [ 0.        ,  0.        ,  0.        ,  1.        , -0.00843476,
        -0.00488232],
       [ 1.        ,  0.01775331, -0.00843476,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        , -0.00160533,
         0.01775331]])

In [11]:
b

array([ 7.37754225e-03, -1.30962462e-02,  3.58285854e-03,  9.51749142e-04,
        9.13072294e-03,  4.40677256e-03,  7.25442769e-03,  6.70493359e-03,
        1.09283030e-02,  3.42404334e-03,  1.32291720e-02,  1.72299700e-03,
        7.51217683e-03,  6.85245353e-03,  2.10977512e-02,  3.36154532e-03,
        9.37767894e-03,  3.26925188e-03, -3.34090025e-03,  5.78495748e-03,
       -6.75766508e-03, -4.58541841e-03,  1.64714879e-03,  8.42445324e-03,
       -4.35700186e-02,  1.67003886e-02, -1.23938763e-03, -6.57485926e-03,
        1.29942244e-02,  1.18366113e-02,  3.07961316e-03,  8.14397958e-03,
        1.01903371e-02,  1.16346557e-03,  1.27912876e-03, -7.12970496e-03,
        5.05232930e-03,  7.57392218e-03,  5.16659909e-03,  1.07426271e-03,
       -3.00946929e-03, -3.20516789e-03,  4.00780799e-03,  2.28179153e-03,
        6.04329766e-03,  2.45047559e-03,  2.07991089e-03, -9.31181719e-03,
       -6.28883184e-03, -5.89171579e-03,  1.14761669e-02,  9.67927593e-03,
        3.42449311e-03,  6.11573440e-04, -1.18231920e-02,  4.41844874e-03,
       -1.01461082e-02, -2.41319532e-03,  4.06276889e-04, -5.55078704e-04,
        5.80228578e-04,  1.24632469e-02,  7.52899675e-03, -4.88157233e-03,
       -7.32508584e-03, -9.57193780e-03,  4.60211680e-04, -7.46656342e-03,
        7.92177360e-03,  2.60445100e-02,  8.87640770e-04,  6.46815323e-03,
       -1.17658981e-04, -2.41444026e-03,  9.86711255e-04, -6.77974849e-03,
       -2.90638764e-03,  2.45626408e-03,  2.86612891e-03, -1.53264252e-03,
       -8.40440113e-03,  1.86258007e-02,  1.20239588e-02,  1.38212180e-02,
        4.90440010e-03, -1.12996791e-03, -4.54661150e-03, -9.80323343e-03,
        1.48014879e-02,  3.27053376e-03,  1.42462965e-02,  2.10104464e-03,
        6.87952192e-03,  4.89598958e-03, -7.53347427e-03,  1.48045042e-02,
        1.38282923e-03, -5.53087091e-03,  5.73681373e-03,  2.34028307e-03,
        5.35916275e-03,  3.79873296e-03, -1.34162611e-02, -3.91027817e-03,
       -6.18181994e-03,  8.37726992e-03,  3.22104846e-03,  7.05140249e-03,
        9.63771251e-04,  6.75100666e-03,  2.04748689e-03,  8.96254599e-04,
        3.34145000e-03,  3.14947931e-03,  2.27606707e-02,  6.79108338e-04,
       -7.76098189e-03,  3.81862419e-03, -4.15396146e-03, -1.71225795e-02,
       -4.15479099e-03,  1.87910576e-02, -1.23271482e-03, -1.56321158e-02,
        2.07851415e-02, -3.64113189e-03,  2.22936148e-02,  3.76328557e-03,
        1.85001942e-02,  4.53900981e-03,  7.96263590e-03,  2.87415360e-03,
        1.10931673e-03,  3.92220892e-03,  6.36377764e-03,  4.72685039e-03,
        3.74310143e-03, -2.86380509e-03, -1.10638511e-03,  1.20621578e-02,
       -1.69990285e-03,  9.95775562e-04,  1.11080788e-02,  8.21838112e-03,
        1.20845586e-02, -3.54082606e-03,  1.56798343e-03, -7.99243602e-04,
       -2.85456493e-03,  1.16680300e-02,  2.23707246e-03,  5.59379150e-03,
       -1.09313662e-02,  1.58187040e-02,  1.12716022e-02,  5.40967008e-03,
        1.30345661e-03,  7.02818145e-03,  1.28066657e-02,  1.93561470e-02,
        1.42439930e-02,  7.52862557e-03,  1.27230546e-02,  1.16923364e-02,
        6.25878719e-03,  1.02407465e-02,  1.05322623e-02,  4.62177773e-03,
       -4.37640108e-04,  4.00051080e-03, -5.65330720e-03, -9.23642271e-03,
        4.54970856e-03,  6.58369334e-03,  6.03578636e-03,  6.97864297e-03,
       -1.26576911e-02,  7.17560225e-03,  1.38354384e-02,  1.24494977e-02,
        1.25058111e-02,  7.73462530e-03,  6.84655726e-03,  2.80540876e-03,
        5.95303191e-03, -5.19962839e-03,  1.21138263e-02, -2.56958100e-03,
        5.92055985e-03,  1.33546826e-02,  1.21649816e-02,  2.44980343e-02,
       -7.18696240e-03, -3.73020219e-03,  1.09548310e-02, -6.14765970e-03,
       -6.05661270e-03,  5.31801811e-03, -9.07864513e-03,  1.89281246e-03,
        4.74014210e-03,  3.98047931e-03,  4.80257386e-03, -2.53836403e-03,
        1.09545735e-03, -1.62972485e-03, -4.19549993e-02, -4.27647802e-03,
       -9.47685187e-03, -3.36885346e-03, -1.79459867e-03,  8.42022821e-03,
        2.87276683e-03,  2.27579190e-03,  3.09288799e-03, -2.25438845e-03,
       -7.58314895e-03,  7.81610028e-03, -8.36135421e-03, -7.20660188e-03,
        5.31369313e-04,  8.33823341e-03, -6.33569077e-04, -6.46090770e-03,
       -5.43704154e-04,  2.38144944e-03, -7.01387458e-04,  7.62915166e-03,
        1.22536440e-02,  4.27745452e-03,  1.94025874e-02,  7.33357552e-03,
        1.38836690e-02,  8.36905744e-03,  7.49158146e-03, -8.50657585e-03,
       -7.76194445e-03, -5.91756072e-04,  8.41370851e-03,  6.32589470e-03,
        1.64790943e-03,  7.49784739e-03,  1.20503057e-02,  5.31295179e-03,
        5.81788124e-03,  4.21816106e-03,  2.68177206e-03, -3.64330173e-03,
       -6.85346232e-03,  6.13791599e-03,  1.10313950e-02,  2.58206297e-03,
        7.79087976e-04, -1.26985237e-02, -1.31559984e-02,  1.44927608e-02,
       -1.94809757e-03, -2.48563274e-02,  2.59175046e-02,  1.01712380e-03,
       -8.14150348e-03, -3.80427079e-02,  1.35773929e-02, -4.41722157e-03,
        1.26778685e-02, -2.87379357e-03, -2.30262709e-03, -3.70568020e-03,
        1.27881986e-03,  1.39667515e-02, -2.40946229e-03,  2.64329969e-03,
        7.01936298e-03,  1.27017810e-02, -9.15082055e-04, -7.97042310e-03,
        2.97352374e-06, -5.69923690e-04, -8.89736714e-03,  6.99897585e-03,
        6.81220842e-03,  2.01838611e-02,  4.77042280e-03, -3.54710993e-03,
       -7.28470550e-03,  4.03701104e-03, -4.34360478e-03,  6.01682901e-03,
       -2.65385101e-03,  9.99055289e-04,  9.40860085e-04, -5.36284951e-03,
       -1.10766342e-02,  1.25748170e-02,  6.44344434e-03, -4.88232373e-03,
       -8.43475855e-03,  1.77533103e-02, -1.60533334e-03,  1.14828326e-02])

In [12]:
A.shape, b.shape

((300, 6), (300,))

In [13]:
b[:5]

array([ 0.00737754, -0.01309625,  0.00358286,  0.00095175,  0.00913072])

## Penyelesaian via Persamaan Normal

In [14]:
A_normal = A.T @ A
b_normal = A.T @ b

In [15]:
A_normal

array([[ 1.95000000e+02,  1.44561911e+00,  6.24790298e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 1.44561911e+00,  1.68323857e-02,  2.82513509e-03,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 6.24790298e-01,  2.82513509e-03,  1.91107639e-02,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.05000000e+02, -7.04398054e-01,  1.20474096e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -7.04398054e-01,  1.01917668e-02, -8.19610043e-05],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.20474096e-01, -8.19610043e-05,  7.91675532e-03]])

In [16]:
b_normal

array([ 0.6477362 ,  0.00555468,  0.00460568,  0.11328741, -0.00280966,
       -0.00098588])

In [17]:
A_normal.shape, b_normal.shape

((6, 6), (6,))

In [18]:
normal_system = np.concatenate((A_normal, b_normal.reshape(-1, 1)), axis=1)

In [19]:
normal_system

array([[ 1.95000000e+02,  1.44561911e+00,  6.24790298e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         6.47736199e-01],
       [ 1.44561911e+00,  1.68323857e-02,  2.82513509e-03,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         5.55468491e-03],
       [ 6.24790298e-01,  2.82513509e-03,  1.91107639e-02,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         4.60567578e-03],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.05000000e+02, -7.04398054e-01,  1.20474096e-01,
         1.13287411e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -7.04398054e-01,  1.01917668e-02, -8.19610043e-05,
        -2.80966113e-03],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.20474096e-01, -8.19610043e-05,  7.91675532e-03,
        -9.85884084e-04]])

In [20]:
# credit to https://www.geeksforgeeks.org/dsa/gaussian-elimination/
def gaussianElimination(mat, N=3):
    for k in range(N):
        i_max = max(range(k, N), key=lambda i: abs(mat[i][k]))
        if mat[i_max][k] == 0:
            print("Singular Matrix.")
            print("Inconsistent System." if mat[i_max][N]
                  else "May have infinitely many solutions.")
            return
        mat[k], mat[i_max] = mat[i_max], mat[k]

        for i in range(k + 1, N):
            f = mat[i][k] / mat[k][k]
            mat[i][k + 1:] = [mat[i][j] - f * mat[k][j]
                              for j in range(k + 1, N + 1)]
            mat[i][k] = 0

    x = [0] * N
    for i in range(N - 1, -1, -1):
        x[i] = (mat[i][N] - sum(mat[i][j] * x[j]
                for j in range(i + 1, N))) / mat[i][i]

    print("\nSolution for the system:")
    for xi in x:
        print(f"{xi:.8f}")

    return np.array(x)

In [21]:
normal_soln = gaussianElimination(normal_system, N=normal_system.shape[0])

Solution for the system:
0.00151337
0.17215290
0.16607285
-0.00121269
-0.36037682
-0.10980804

In [22]:
np.linalg.norm(A @ normal_soln - b)

0.15297704991440925

### iii.b Perhitungan Condition Number

In [23]:
np.linalg.cond(A)

192.60541021575767

In [24]:
np.linalg.cond(A_normal)

37096.84404438027

### iii.c Analisis pengaruh condition Number

In [25]:
b_perturbed = b + np.random.normal(0, 0.1, size=b.size)

In [26]:
b_diff = abs(b - b_perturbed)

In [27]:
print(f"mean perturbation: {b_diff.mean()}")
print(f"max perturbation: {b_diff.max()}")

mean perturbation: 0.08177699612940648
max perturbation: 0.2829480312052178

In [28]:
b_pert_normal = A.T @ b_perturbed

In [29]:
perturbed_normal_system = np.concatenate((A_normal, b_pert_normal.reshape(-1, 1)), axis=1)

In [30]:
perturbed_normal_soln = gaussianElimination(perturbed_normal_system, N=normal_system.shape[0])

Solution for the system:
0.01065396
-0.54784499
0.31958223
0.00760061
0.49533190
-0.90324858

In [31]:
normal_diff = abs(perturbed_normal_soln - normal_soln)

In [32]:
print(f"mean perturbation: {normal_diff.mean()}")
print(f"max perturbation: {normal_diff.max()}")

mean perturbation: 0.4234350700987039
max perturbation: 0.8557087263946916

In [33]:
def givens(mat):
    Q = np.eye(mat.shape[0])
    for i in range(mat.shape[1]):
        for j in range(i+1, mat.shape[0]):
            if mat[j, i] == 0: continue

            G = np.eye(mat.shape[0])
            alpha = np.sqrt(mat[j, i]**2 + mat[i, i]**2)
            s = mat[j, i]/alpha
            c= mat[i, i]/alpha
            G[i, i] = c
            G[j, j] = c
            G[i, j] = s
            G[j, i] = -s

            # Verifikasi algoritma, menjawab (iv.c)

            print(f"G_k untuk mengeliminasi elemen {(j+1, i+1)}:\n" + str(G))

            mat = G @ mat
            Q = G @ Q

            print("Hasil G_k @ A:\n" + str(mat))

            print(f"Apakah elemen {(j+1, i+1)} (mendekati) 0: " + str(abs(mat[j, i]) < 1e-9) +"\n\n\n")


    return Q, mat

In [34]:
test = np.linspace(1, 12, 12).reshape(4, 3)

In [35]:
test

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [36]:
givens(test)

G_k untuk mengeliminasi elemen (2, 1):
[[ 0.24253563  0.9701425   0.          0.        ]
 [-0.9701425   0.24253563  0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]
Hasil G_k @ A:
[[ 4.12310563  5.33578375  6.54846188]
 [ 0.         -0.72760688 -1.45521375]
 [ 7.          8.          9.        ]
 [10.         11.         12.        ]]
Apakah elemen (2, 1) (mendekati) 0: True



G_k untuk mengeliminasi elemen (3, 1):
[[ 0.50751922  0.          0.86164044  0.        ]
 [ 0.          1.          0.          0.        ]
 [-0.86164044  0.          0.50751922  0.        ]
 [ 0.          0.          0.          1.        ]]
Hasil G_k @ A:
[[ 8.12403840e+00  9.60113630e+00  1.10782342e+01]
 [ 0.00000000e+00 -7.27606875e-01 -1.45521375e+00]
 [-3.33066907e-16 -5.37373291e-01 -1.07474658e+00]
 [ 1.00000000e+01  1.10000000e+01  1.20000000e+01]]
Apakah elemen (3, 1) (mendekati) 0: True



G_k untuk mengeliminasi elemen (4, 1):
[[ 0.63054767  0.          0.          0.77615053]
 [ 0.          1.          0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [-0.77615053  0.          0.          0.63054767]]
Hasil G_k @ A:
[[ 1.28840987e+01  1.45916299e+01  1.62991610e+01]
 [ 0.00000000e+00 -7.27606875e-01 -1.45521375e+00]
 [-3.33066907e-16 -5.37373291e-01 -1.07474658e+00]
 [ 2.22044605e-16 -5.15902637e-01 -1.03180527e+00]]
Apakah elemen (4, 1) (mendekati) 0: True



G_k untuk mengeliminasi elemen (3, 2):
[[ 1.          0.          0.          0.        ]
 [ 0.         -0.80439967 -0.59408853  0.        ]
 [ 0.          0.59408853 -0.80439967  0.        ]
 [ 0.          0.          0.          1.        ]]
Hasil G_k @ A:
[[ 1.28840987e+01  1.45916299e+01  1.62991610e+01]
 [ 1.97871228e-16  9.04534034e-01  1.80906807e+00]
 [ 2.67918909e-16  2.79373956e-17  5.58747912e-17]
 [ 2.22044605e-16 -5.15902637e-01 -1.03180527e+00]]
Apakah elemen (3, 2) (mendekati) 0: True



G_k untuk mengeliminasi elemen (4, 2):
[[ 1.          0.          0.          0.        ]
 [ 0.          0.86864576  0.         -0.49543369]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.49543369  0.          0.86864576]]
Hasil G_k @ A:
[[ 1.28840987e+01  1.45916299e+01  1.62991610e+01]
 [ 6.18716241e-17  1.04131520e+00  2.08263040e+00]
 [ 2.67918909e-16  2.79373956e-17  5.58747912e-17]
 [ 2.90910178e-16 -1.64878856e-18 -9.67688099e-16]]
Apakah elemen (4, 2) (mendekati) 0: True



G_k untuk mengeliminasi elemen (4, 3):
[[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 0.          0.          0.05764448 -0.99833717]
 [ 0.          0.          0.99833717  0.05764448]]
Hasil G_k @ A:
[[ 1.28840987e+01  1.45916299e+01  1.62991610e+01]
 [ 6.18716241e-17  1.04131520e+00  2.08263040e+00]
 [-2.74982398e-16  3.25648366e-18  9.69299876e-16]
 [ 2.84242774e-16  2.77958970e-17 -5.97829486e-33]]
Apakah elemen (4, 3) (mendekati) 0: True

(array([[ 0.07761505,  0.31046021,  0.54330537,  0.77615053],
        [ 0.83305216,  0.45123659,  0.06942101, -0.31239456],
        [-0.38807446,  0.22933712,  0.70554913, -0.54681179],
        [-0.38652066,  0.80461449, -0.44966702,  0.03157318]]),
 array([[ 1.28840987e+01,  1.45916299e+01,  1.62991610e+01],
        [ 6.18716241e-17,  1.04131520e+00,  2.08263040e+00],
        [-2.74982398e-16,  3.25648366e-18,  9.69299876e-16],
        [ 2.84242774e-16,  2.77958970e-17, -5.97829486e-33]]))

### iv.b Penyelesaian Metode QR Givens Rotation

In [37]:
Q, R = givens(A)

G_k untuk mengeliminasi elemen (2, 1):
[[ 0.  1.  0. ...  0.  0.  0.]
 [-1.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  1. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  1.  0.  0.]
 [ 0.  0.  0. ...  0.  1.  0.]
 [ 0.  0.  0. ...  0.  0.  1.]]
Hasil G_k @ A:
[[ 1.          0.00737754 -0.00831972  0.          0.          0.        ]
 [ 0.          0.          0.         -1.          0.00831972 -0.002438  ]
 [ 0.          0.          0.          1.         -0.01309625  0.00737754]
 ...
 [ 0.          0.          0.          1.         -0.00843476 -0.00488232]
 [ 1.          0.01775331 -0.00843476  0.          0.          0.        ]
 [ 0.          0.          0.          1.         -0.00160533  0.01775331]]
Apakah elemen (2, 1) (mendekati) 0: True



G_k untuk mengeliminasi elemen (4, 1):
[[0.70710678 0.         0.         ... 0.         0.         0.        ]
 [0.         1.         0.         ... 0.         0.         0.        ]
 [0.         0.         1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]
Hasil G_k @ A:
[[ 1.41421356  0.00775017 -0.01514337  0.          0.          0.        ]
 [ 0.          0.          0.         -1.          0.00831972 -0.002438  ]
 [ 0.          0.          0.          1.         -0.01309625  0.00737754]
 ...
 [ 0.          0.          0.          1.         -0.00843476 -0.00488232]
 [ 1.          0.01775331 -0.00843476  0.          0.          0.        ]
 [ 0.          0.          0.          1.         -0.00160533  0.01775331]]
Apakah elemen (4, 1) (mendekati) 0: True



G_k untuk mengeliminasi elemen (5, 1):
[[0.81649658 0.         0.         ... 0.         0.         0.        ]
 [0.         1.         0.         ... 0.         0.         0.        ]
 [0.         0.         1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]
Hasil G_k @ A:
[[ 1.73205081e+00  6.87748297e-03 -1.02959475e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.00000000e+00
   8.31971653e-03 -2.43800000e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.30962462e-02  7.37754225e-03]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -8.43475855e-03 -4.88232373e-03]
 [ 1.00000000e+00  1.77533103e-02 -8.43475855e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.60533334e-03  1.77533103e-02]]
Apakah elemen (5, 1) (mendekati) 0: True



G_k untuk mengeliminasi elemen (6, 1):
[[0.8660254 0.        0.        ... 0.        0.        0.       ]
 [0.        1.        0.        ... 0.        0.        0.       ]
 [0.        0.        1.        ... 0.        0.        0.       ]
 ...
 [0.        0.        0.        ... 1.        0.        0.       ]
 [0.        0.        0.        ... 0.        1.        0.       ]
 [0.        0.        0.        ... 0.        0.        1.       ]]
Hasil G_k @ A:
[[ 2.00000000e+00  1.05214364e-02 -8.44067751e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.00000000e+00
   8.31971653e-03 -2.43800000e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.30962462e-02  7.37754225e-03]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -8.43475855e-03 -4.88232373e-03]
 [ 1.00000000e+00  1.77533103e-02 -8.43475855e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.60533334e-03  1.77533103e-02]]
Apakah elemen (6, 1) (mendekati) 0: True



G_k untuk mengeliminasi elemen (7, 1):
[[0.89442719 0.         0.         ... 0.         0.         0.        ]
 [0.         1.         0.         ... 0.         0.         0.        ]
 [0.         0.         1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]
Hasil G_k @ A:
[[ 2.23606798e+00  1.13814274e-02 -3.46618804e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.00000000e+00
   8.31971653e-03 -2.43800000e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.30962462e-02  7.37754225e-03]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -8.43475855e-03 -4.88232373e-03]
 [ 1.00000000e+00  1.77533103e-02 -8.43475855e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.60533334e-03  1.77533103e-02]]
Apakah elemen (7, 1) (mendekati) 0: True



G_k untuk mengeliminasi elemen (8, 1):
[[0.91287093 0.         0.         ... 0.         0.         0.        ]
 [0.         1.         0.         ... 0.         0.         0.        ]
 [0.         0.         1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]
Hasil G_k @ A:
[[ 2.44948974e+00  1.33513819e-02 -1.36512494e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.00000000e+00
   8.31971653e-03 -2.43800000e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.30962462e-02  7.37754225e-03]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -8.43475855e-03 -4.88232373e-03]
 [ 1.00000000e+00  1.77533103e-02 -8.43475855e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.60533334e-03  1.77533103e-02]]
Apakah elemen (8, 1) (mendekati) 0: True



G_k untuk mengeliminasi elemen (9, 1):
[[0.9258201 0.        0.        ... 0.        0.        0.       ]
 [0.        1.        0.        ... 0.        0.        0.       ]
 [0.        0.        1.        ... 0.        0.        0.       ]
 ...
 [0.        0.        0.        ... 1.        0.        0.       ]
 [0.        0.        0.        ... 0.        1.        0.       ]
 [0.        0.        0.        ... 0.        0.        1.       ]]
Hasil G_k @ A:
[[ 2.64575131e+00  1.48952045e-02  1.47805583e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.00000000e+00
   8.31971653e-03 -2.43800000e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.30962462e-02  7.37754225e-03]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -8.43475855e-03 -4.88232373e-03]
 [ 1.00000000e+00  1.77533103e-02 -8.43475855e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.60533334e-03  1.77533103e-02]]
Apakah elemen (9, 1) (mendekati) 0: True



G_k untuk mengeliminasi elemen (10, 1):
[[0.93541435 0.         0.         ... 0.         0.         0.        ]
 [0.         1.         0.         ... 0.         0.         0.        ]
 [0.         0.         1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]
Hasil G_k @ A:
[[ 2.82842712e+00  1.77969265e-02  3.75314664e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.00000000e+00
   8.31971653e-03 -2.43800000e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.30962462e-02  7.37754225e-03]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -8.43475855e-03 -4.88232373e-03]
 [ 1.00000000e+00  1.77533103e-02 -8.43475855e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.60533334e-03  1.77533103e-02]]
Apakah elemen (10, 1) (mendekati) 0: True



G_k untuk mengeliminasi elemen (11, 1):
[[0.94280904 0.         0.         ... 0.         0.         0.        ]
 [0.         1.         0.         ... 0.         0.         0.        ]
 [0.         0.         1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]
Hasil G_k @ A:
[[ 3.00000000e+00  1.79204510e-02  7.18126826e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.00000000e+00
   8.31971653e-03 -2.43800000e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.30962462e-02  7.37754225e-03]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -8.43475855e-03 -4.88232373e-03]
 [ 1.00000000e+00  1.77533103e-02 -8.43475855e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.60533334e-03  1.77533103e-02]]
Apakah elemen (11, 1) (mendekati) 0: True



G_k untuk mengeliminasi elemen (12, 1):
[[0.9486833 0.        0.        ... 0.        0.        0.       ]
 [0.        1.        0.        ... 0.        0.        0.       ]
 [0.        0.        1.        ... 0.        0.        0.       ]
 ...
 [0.        0.        0.        ... 1.        0.        0.       ]
 [0.        0.        0.        ... 0.        1.        0.       ]
 [0.        0.        0.        ... 0.        0.        1.       ]]
Hasil G_k @ A:
[[ 3.16227766e+00  2.11842641e-02  7.89552684e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.00000000e+00
   8.31971653e-03 -2.43800000e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.30962462e-02  7.37754225e-03]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -8.43475855e-03 -4.88232373e-03]
 [ 1.00000000e+00  1.77533103e-02 -8.43475855e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.60533334e-03  1.77533103e-02]]
Apakah elemen (12, 1) (mendekati) 0: True



G_k untuk mengeliminasi elemen (13, 1):
[[0.95346259 0.         0.         ... 0.         0.         0.        ]
 [0.         1.         0.         ... 0.         0.         0.        ]
 [0.         0.         1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]
Hasil G_k @ A:
[[ 3.31662479e+00  2.07179064e-02  1.15168349e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.00000000e+00
   8.31971653e-03 -2.43800000e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.30962462e-02  7.37754225e-03]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -8.43475855e-03 -4.88232373e-03]
 [ 1.00000000e+00  1.77533103e-02 -8.43475855e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.60533334e-03  1.77533103e-02]]
Apakah elemen (13, 1) (mendekati) 0: True



G_k untuk mengeliminasi elemen (14, 1):
[[0.95742711 0.         0.         ... 0.         0.         0.        ]
 [0.         1.         0.         ... 0.         0.         0.        ]
 [0.         0.         1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]
Hasil G_k @ A:
[[ 3.46410162e+00  2.20044639e-02  1.15239163e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.00000000e+00
   8.31971653e-03 -2.43800000e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.30962462e-02  7.37754225e-03]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -8.43475855e-03 -4.88232373e-03]
 [ 1.00000000e+00  1.77533103e-02 -8.43475855e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.60533334e-03  1.77533103e-02]]
Apakah elemen (14, 1) (mendekati) 0: True



G_k untuk mengeliminasi elemen (15, 1):
[[0.96076892 0.         0.         ... 0.         0.         0.        ]
 [0.         1.         0.         ... 0.         0.         0.        ]
 [0.         0.         1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]
Hasil G_k @ A:
[[ 3.60555128e+00  2.30417337e-02  1.31553236e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.00000000e+00
   8.31971653e-03 -2.43800000e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.30962462e-02  7.37754225e-03]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -8.43475855e-03 -4.88232373e-03]
 [ 1.00000000e+00  1.77533103e-02 -8.43475855e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.60533334e-03  1.77533103e-02]]
Apakah elemen (15, 1) (mendekati) 0: True



G_k untuk mengeliminasi elemen (16, 1):
[[0.96362411 0.         0.         ... 0.         0.         0.        ]
 [0.         1.         0.         ... 0.         0.         0.        ]
 [0.         0.         1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]
Hasil G_k @ A:
[[ 3.74165739e+00  2.78421814e-02  1.45081823e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.00000000e+00
   8.31971653e-03 -2.43800000e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.30962462e-02  7.37754225e-03]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -8.43475855e-03 -4.88232373e-03]
 [ 1.00000000e+00  1.77533103e-02 -8.43475855e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.60533334e-03  1.77533103e-02]]
Apakah elemen (16, 1) (mendekati) 0: True



G_k untuk mengeliminasi elemen (17, 1):
[[0.96609178 0.         0.         ... 0.         0.         0.        ]
 [0.         1.         0.         ... 0.         0.         0.        ]
 [0.         0.         1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]
Hasil G_k @ A:
[[ 3.87298335e+00  2.77660499e-02  1.94636516e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.00000000e+00
   8.31971653e-03 -2.43800000e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.30962462e-02  7.37754225e-03]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -8.43475855e-03 -4.88232373e-03]
 [ 1.00000000e+00  1.77533103e-02 -8.43475855e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.60533334e-03  1.77533103e-02]]
Apakah elemen (17, 1) (mendekati) 0: True



G_k untuk mengeliminasi elemen (18, 1):
[[0.96824584 0.         0.         ... 0.         0.         0.        ]
 [0.         1.         0.         ... 0.         0.         0.        ]
 [0.         0.         1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]
Hasil G_k @ A:
[[ 4.00000000e+00  2.92287820e-02  1.96859860e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.00000000e+00
   8.31971653e-03 -2.43800000e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.30962462e-02  7.37754225e-03]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -8.43475855e-03 -4.88232373e-03]
 [ 1.00000000e+00  1.77533103e-02 -8.43475855e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.60533334e-03  1.77533103e-02]]
Apakah elemen (18, 1) (mendekati) 0: True



G_k untuk mengeliminasi elemen (19, 1):
[[0.9701425 0.        0.        ... 0.        0.        0.       ]
 [0.        1.        0.        ... 0.        0.        0.       ]
 [0.        0.        1.        ... 0.        0.        0.       ]
 ...
 [0.        0.        0.        ... 1.        0.        0.       ]
 [0.        0.        0.        ... 0.        1.        0.       ]
 [0.        0.        0.        ... 0.        0.        1.       ]]
Hasil G_k @ A:
[[ 4.12310563e+00  2.91489937e-02  2.13726329e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.00000000e+00
   8.31971653e-03 -2.43800000e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.30962462e-02  7.37754225e-03]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -8.43475855e-03 -4.88232373e-03]
 [ 1.00000000e+00  1.77533103e-02 -8.43475855e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.60533334e-03  1.77533103e-02]]
Apakah elemen (19, 1) (mendekati) 0: True



G_k untuk mengeliminasi elemen (21, 1):
[[0.97182532 0.         0.         ... 0.         0.         0.        ]
 [0.         1.         0.         ... 0.         0.         0.        ]
 [0.         0.         1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]
Hasil G_k @ A:
[[ 4.24264069e+00  2.96912575e-02  1.99830080e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.00000000e+00
   8.31971653e-03 -2.43800000e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.30962462e-02  7.37754225e-03]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -8.43475855e-03 -4.88232373e-03]
 [ 1.00000000e+00  1.77533103e-02 -8.43475855e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]

Hasil G_k @ A:
[[ 1.39642400e+01  1.03522935e-01  4.47421625e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 2.09685097e-17  7.82009438e-02 -2.31033643e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-2.27846504e-17  9.96645910e-20  5.32604091e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -8.43475855e-03 -4.88232373e-03]
 [-2.80438260e-18  0.00000000e+00 -8.68276372e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.60533334e-03  1.77533103e-02]]
Apakah elemen (27, 3) (mendekati) 0: True



G_k untuk mengeliminasi elemen (30, 3):
[[1.         0.         0.         ... 0.         0.         0.        ]
 [0.         1.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.99848097 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]
Hasil G_k @ A:
[[ 1.39642400e+01  1.03522935e-01  4.47421625e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 2.09685097e-17  7.82009438e-02 -2.31033643e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-2.27795907e-17  1.01361676e-19  5.33414364e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -8.43475855e-03 -4.88232373e-03]
 [-2.80438260e-18  0.00000000e+00 -8.68276372e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.60533334e-03  1.77533103e-02]]
Apakah elemen (30, 3) (mendekati) 0: True



G_k untuk mengeliminasi elemen (31, 3):
[[1.         0.         0.         ... 0.         0.         0.        ]
 [0.         1.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.96226348 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]
Hasil G_k @ A:
[[ 1.39642400e+01  1.03522935e-01  4.47421625e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 2.09685097e-17  7.82009438e-02 -2.31033643e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-2.18149853e-17 -4.73830434e-20  5.54332959e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -8.43475855e-03 -4.88232373e-03]
 [-2.80438260e-18  0.00000000e+00 -8.68276372e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.60533334e-03  1.77533103e-02]]
Apakah elemen (31, 3) (mendekati) 0: True



G_k untuk mengeliminasi elemen (32, 3):
[[1.         0.         0.         ... 0.         0.         0.        ]
 [0.         1.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.99465642 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]
Hasil G_k @ A:
[[ 1.39642400e+01  1.03522935e-01  4.47421625e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 2.09685097e-17  7.82009438e-02 -2.31033643e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-2.17399679e-17 -2.33503446e-20  5.57310997e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -8.43475855e-03 -4.88232373e-03]
 [-2.80438260e-18  0.00000000e+00 -8.68276372e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.60533334e-03  1.77533103e-02]]
Apakah elemen (32, 3) (mendekati) 0: True



G_k untuk mengeliminasi elemen (33, 3):
[[1.         0.         0.         ... 0.         0.         0.        ]
 [0.         1.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.99975019 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]
Hasil G_k @ A:
[[ 1.39642400e+01  1.03522935e-01  4.47421625e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 2.09685097e-17  7.82009438e-02 -2.31033643e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-1.92527054e-17 -2.28459410e-20  5.57450254e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -8.43475855e-03 -4.88232373e-03]
 [-2.80438260e-18  0.00000000e+00 -8.68276372e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.60533334e-03  1.77533103e-02]]
Apakah elemen (33, 3) (mendekati) 0: True



G_k untuk mengeliminasi elemen (34, 3):
[[1.         0.         0.         ... 0.         0.         0.        ]
 [0.         1.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.99011496 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]
Hasil G_k @ A:
[[ 1.39642400e+01  1.03522935e-01  4.47421625e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 2.09685097e-17  7.82009438e-02 -2.31033643e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-3.58979565e-18 -4.44952675e-20  5.63015688e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -8.43475855e-03 -4.88232373e-03]
 [-2.80438260e-18  0.00000000e+00 -8.68276372e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.60533334e-03  1.77533103e-02]]
Apakah elemen (34, 3) (mendekati) 0: True



G_k untuk mengeliminasi elemen (35, 3):
[[1.         0.         0.         ... 0.         0.         0.        ]
 [0.         1.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.99939969 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]
Hasil G_k @ A:
[[ 1.39642400e+01  1.03522935e-01  4.47421625e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 2.09685097e-17  7.82009438e-02 -2.31033643e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-3.47735570e-18 -2.39709173e-20  5.63353878e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -8.43475855e-03 -4.88232373e-03]
 [-2.80438260e-18  0.00000000e+00 -8.68276372e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.60533334e-03  1.77533103e-02]]
Apakah elemen (35, 3) (mendekati) 0: True



G_k untuk mengeliminasi elemen (36, 3):
[[1.        0.        0.        ... 0.        0.        0.       ]
 [0.        1.        0.        ... 0.        0.        0.       ]
 [0.        0.        0.9928901 ... 0.        0.        0.       ]
 ...
 [0.        0.        0.        ... 1.        0.        0.       ]
 [0.        0.        0.        ... 0.        1.        0.       ]
 [0.        0.        0.        ... 0.        0.        1.       ]]
Hasil G_k @ A:
[[ 1.39642400e+01  1.03522935e-01  4.47421625e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 2.09685097e-17  7.82009438e-02 -2.31033643e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-3.78966312e-18 -1.38643331e-20  5.67387952e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -8.43475855e-03 -4.88232373e-03]
 [-2.80438260e-18  0.00000000e+00 -8.68276372e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.60533334e-03  1.77533103e-02]]
Apakah elemen (36, 3) (mendekati) 0: True



G_k untuk mengeliminasi elemen (38, 3):
[[1.         0.         0.         ... 0.         0.         0.        ]
 [0.         1.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.98025039 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]
Hasil G_k @ A:
[[ 1.39642400e+01  1.03522935e-01  4.47421625e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 2.09685097e-17  7.82009438e-02 -2.31033643e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-3.90439377e-18 -3.60199553e-20  5.78819408e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -8.43475855e-03 -4.88232373e-03]
 [-2.80438260e-18  0.00000000e+00 -8.68276372e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.60533334e-03  1.77533103e-02]]
Apakah elemen (38, 3) (mendekati) 0: True



G_k untuk mengeliminasi elemen (39, 3):
[[1.         0.         0.         ... 0.         0.         0.        ]
 [0.         1.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.99877145 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]
Hasil G_k @ A:
[[ 1.39642400e+01  1.03522935e-01  4.47421625e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 2.09685097e-17  7.82009438e-02 -2.31033643e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 1.59114630e-18 -3.69027691e-20  5.79531395e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -8.43475855e-03 -4.88232373e-03]
 [-2.80438260e-18  0.00000000e+00 -8.68276372e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.60533334e-03  1.77533103e-02]]
Apakah elemen (39, 3) (mendekati) 0: True



G_k untuk mengeliminasi elemen (40, 3):
[[1.         0.         0.         ... 0.         0.         0.        ]
 [0.         1.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.99826154 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]
Hasil G_k @ A:
[[ 1.39642400e+01  1.03522935e-01  4.47421625e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 2.09685097e-17  7.82009438e-02 -2.31033643e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 1.64846924e-18 -2.74780488e-20  5.80540641e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -8.43475855e-03 -4.88232373e-03]
 [-2.80438260e-18  0.00000000e+00 -8.68276372e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.60533334e-03  1.77533103e-02]]
Apakah elemen (40, 3) (mendekati) 0: True



G_k untuk mengeliminasi elemen (41, 3):
[[1.         0.         0.         ... 0.         0.         0.        ]
 [0.         1.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.99931053 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]
Hasil G_k @ A:
[[ 1.39642400e+01  1.03522935e-01  4.47421625e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 2.09685097e-17  7.82009438e-02 -2.31033643e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 1.53514391e-18 -3.98671759e-20  5.80941180e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -8.43475855e-03 -4.88232373e-03]
 [-2.80438260e-18  0.00000000e+00 -8.68276372e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.60533334e-03  1.77533103e-02]]
Apakah elemen (41, 3) (mendekati) 0: True



G_k untuk mengeliminasi elemen (44, 3):
[[1.        0.        0.        ... 0.        0.        0.       ]
 [0.        1.        0.        ... 0.        0.        0.       ]
 [0.        0.        0.9905733 ... 0.        0.        0.       ]
 ...
 [0.        0.        0.        ... 1.        0.        0.       ]
 [0.        0.        0.        ... 0.        1.        0.       ]
 [0.        0.        0.        ... 0.        0.        1.       ]]
Hasil G_k @ A:
[[ 1.39642400e+01  1.03522935e-01  4.47421625e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 2.09685097e-17  7.82009438e-02 -2.31033643e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 1.64508796e-17 -3.24839790e-20  5.86469652e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -8.43475855e-03 -4.88232373e-03]
 [-2.80438260e-18  0.00000000e+00 -8.68276372e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.60533334e-03  1.77533103e-02]]
Apakah elemen (44, 3) (mendekati) 0: True



G_k untuk mengeliminasi elemen (45, 3):
[[1.         0.         0.         ... 0.         0.         0.        ]
 [0.         1.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.99949693 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]
Hasil G_k @ A:
[[ 1.39642400e+01  1.03522935e-01  4.47421625e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 2.09685097e-17  7.82009438e-02 -2.31033643e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 1.63127846e-17 -4.35006227e-20  5.86764834e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -8.43475855e-03 -4.88232373e-03]
 [-2.80438260e-18  0.00000000e+00 -8.68276372e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.60533334e-03  1.77533103e-02]]
Apakah elemen (45, 3) (mendekati) 0: True



G_k untuk mengeliminasi elemen (46, 3):
[[1.         0.         0.         ... 0.         0.         0.        ]
 [0.         1.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.99990316 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]
Hasil G_k @ A:
[[ 1.39642400e+01  1.03522935e-01  4.47421625e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 2.09685097e-17  7.82009438e-02 -2.31033643e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 1.63034756e-17 -4.47878628e-20  5.86821660e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -8.43475855e-03 -4.88232373e-03]
 [-2.80438260e-18  0.00000000e+00 -8.68276372e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.60533334e-03  1.77533103e-02]]
Apakah elemen (46, 3) (mendekati) 0: True



G_k untuk mengeliminasi elemen (47, 3):
[[1.         0.         0.         ... 0.         0.         0.        ]
 [0.         1.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.99998062 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]
Hasil G_k @ A:
[[ 1.39642400e+01  1.03522935e-01  4.47421625e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 2.09685097e-17  7.82009438e-02 -2.31033643e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 1.63262602e-17 -4.76711007e-20  5.86833032e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -8.43475855e-03 -4.88232373e-03]
 [-2.80438260e-18  0.00000000e+00 -8.68276372e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.60533334e-03  1.77533103e-02]]
Apakah elemen (47, 3) (mendekati) 0: True



G_k untuk mengeliminasi elemen (48, 3):
[[1.         0.         0.         ... 0.         0.         0.        ]
 [0.         1.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.99831327 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]
Hasil G_k @ A:
[[ 1.39642400e+01  1.03522935e-01  4.47421625e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 2.09685097e-17  7.82009438e-02 -2.31033643e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 2.24403480e-17 -3.13055655e-20  5.87824536e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -8.43475855e-03 -4.88232373e-03]
 [-2.80438260e-18  0.00000000e+00 -8.68276372e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.60533334e-03  1.77533103e-02]]
Apakah elemen (48, 3) (mendekati) 0: True



G_k untuk mengeliminasi elemen (52, 3):
[[1.        0.        0.        ... 0.        0.        0.       ]
 [0.        1.        0.        ... 0.        0.        0.       ]
 [0.        0.        0.9964979 ... 0.        0.        0.       ]
 ...
 [0.        0.        0.        ... 1.        0.        0.       ]
 [0.        0.        0.        ... 0.        1.        0.       ]
 [0.        0.        0.        ... 0.        0.        1.       ]]
Hasil G_k @ A:
[[ 1.39642400e+01  1.03522935e-01  4.47421625e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 2.09685097e-17  7.82009438e-02 -2.31033643e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 2.29769989e-17 -4.61055461e-20  5.89890389e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -8.43475855e-03 -4.88232373e-03]

In [38]:
Q.shape, R.shape

((300, 300), (300, 6))

In [39]:
b.shape

(300,)

In [40]:
d = Q @ b

In [41]:
d_hat = d[:A.shape[1]]

In [42]:
d_hat

array([ 0.04638535,  0.00962568,  0.02138096,  0.01105572, -0.02772282,
       -0.00962437])

In [43]:
R_hat = R[:A.shape[1]]

In [44]:
R_hat

array([[ 1.39642400e+01,  1.03522935e-01,  4.47421625e-02,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 2.09685097e-17,  7.82009438e-02, -2.31033643e-02,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-2.61687088e-17,  4.16129287e-19,  1.28744466e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.02469508e+01, -6.87422112e-02,  1.17570679e-02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -2.80904835e-17,  7.39342629e-02,  9.82285904e-03],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -4.35774769e-18,  2.20701130e-19,  8.76472368e-02]])

In [45]:
givens_system = np.concatenate((R_hat, d_hat.reshape(-1, 1)), axis=1)

In [46]:
def back_subtitution(mat, N=3):
    # for k in range(N):
    #     i_max = max(range(k, N), key=lambda i: abs(mat[i][k]))
    #     if mat[i_max][k] == 0:
    #         print("Singular Matrix.")
    #         print("Inconsistent System." if mat[i_max][N]
    #               else "May have infinitely many solutions.")
    #         return
    #     mat[k], mat[i_max] = mat[i_max], mat[k]

    #     for i in range(k + 1, N):
    #         f = mat[i][k] / mat[k][k]
    #         mat[i][k + 1:] = [mat[i][j] - f * mat[k][j]
    #                           for j in range(k + 1, N + 1)]
    #         mat[i][k] = 0

    x = [0] * N
    for i in range(N - 1, -1, -1):
        x[i] = (mat[i][N] - sum(mat[i][j] * x[j]
                for j in range(i + 1, N))) / mat[i][i]

    print("\nSolution for the system:")
    for xi in x:
        print(f"{xi:.8f}")

    return np.array(x)

In [47]:
givens_soln = back_subtitution(givens_system, A.shape[1])

Solution for the system:
0.00151337
0.17215290
0.16607285
-0.00121269
-0.36037682
-0.10980804

In [48]:
np.linalg.norm(A @ givens_soln - b)

0.15297704991440925